#!/bin/bash

TEMPDIR="./tmp"

function die() {
    echo "$@" >&2
    exit 1
}

declare -a DOCKER_ARGS
DOCKER_ARGS+=( "$@" )

cd $(git rev-parse --show-toplevel)

mkdir "${TEMPDIR}"
STAGE_DIR=$(mktemp -p "${TEMPDIR}" --directory)
if test ! -d "${STAGE_DIR}"; then
    rm -r "${TEMPDIR}"
    die "Failed to create staging directory"
fi

args=( "${DOCKER_ARGS[@]}" )
docker build "${args[@]}" --build-arg "STAGE_DIR=${STAGE_DIR}" \
    -t "test/mpd:latest" -f ./t/docker/Dockerfile.ubuntu .

rm -r "${STAGE_DIR}"
rm -r "${TEMPDIR}"
