name: Test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - v*
  schedule:
    - cron: 5 07 * * FRI

jobs:
  release-build:
    name: Release Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3 
      - name: Generate docker tags
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            jkz0/ashuffle-integration-root
            ghcr.io/joshkunz/ashuffle-integration-root
          tags: |
            type=ref,event=tag
          flavor: |
            latest=true
      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Github Registry
        uses: docker/login-action@v3
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.meta.outputs.tags }}
